name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6e7038e6b6e87000b64d6573a97ce6a3d875c93f7e35aef61c8fc2a4db91f94"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
