name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0db44f879ae07ba6b9e7aa30f22c271dde03cd2c2b531c84bd1cd5c7e2d58a63"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
