name = "Revival 1.21"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df775ce98d00b2367f8171b5d441acad6920f79ffe884fae611339335c680e1"

[versions]
fabric = "0.16.5"
minecraft = "1.21"

[options]
acceptable-game-versions = []
