name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12910982a1c58417068fca4fa97da3b130ef6f20fae47cac6559f4834b6b7a85"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
