name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cbcd505c7deecdebb8a7b3ef9af50c4aa5b70351654ab6b4ea9c8e4979b51c6"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
