name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3abc3544b424611071dd6d6ef9a9d7ad14a8100303c4e04f4502ae9881a44748"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
