name = "Revival 1.21"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b7212cd55bde97676401899d7ad01ea9193fb5f00c018f929a3994aab5215bc"

[versions]
fabric = "0.16.5"
minecraft = "1.21"

[options]
acceptable-game-versions = []
