
[MobTextures]
	#Mobs may spawn with different textures.
	Enabled = true
	#If true, cows may spawn with different textures.
	Cows = false
	#If true, chickens may spawn with different textures.
	Chickens = false
	#If true, dolphins may spawn with different textures.
	Dolphins = true
	#If true, pigs may spawn with different textures.
	Pigs = false
	#If true, sheep face and 'shorn' textures match their wool color.
	Sheep = false
	#If true, snow golems may spawn with different derp faces.
	"Snow golems" = true
	#If true, squids may spawn with different textures.
	Squids = true
	#If true, turtles may spawn with different textures.
	Turtles = true
	#If true, wandering traders may spawn with different textures.
	"Wandering traders" = true

[RepairCostVisible]
	#An item's repair cost is shown in its tooltip when viewing on the anvil.
	Enabled = true

[SpyglassScopeHiding]
	#Removes the border when zooming in with the spyglass.
	Enabled = false

[TooltipImprovements]
	#Adds hover tooltips for some items that have content.
	Enabled = true
	#If true, a map will show its content when hovering over the item.
	Maps = true
	#If true, the contents of a shulker box will be shown when hovering over the item.
	"Shulker boxes" = false

