name = "Revival"
author = "TheCoelho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d214d564cba7ff8d2c4bd9de4afb8f4828c9ad8c53175ee78e18ad767a9b8cc6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
